# References
# 1. https://docs.travis-ci.com/user/build-matrix/

language: r
sudo: false
cache: packages

os:
- linux
- osx

compiler:
- clang
- gcc

exclude:
- os: linux
  compiler: gcc
- os: osx
  compiler: clang

r:
- 3.6.1
- 4.0.2

after_success:
- Rscript -e 'covr::codecov()'
