# References
# 1. https://docs.travis-ci.com/user/build-matrix/

language: r
sudo: false
cache: packages

os:
- linux
- osx
- windows

r:
- 3.5.3
- 3.6.3

after_success:
- Rscript -e 'covr::codecov()'
