testthat::context("Test class 'matrix_list'")

testthat::test_that("Test Constructor and Extractor", {
  set.seed(123)
  a <- new("matrix_list", matrices = purrr::map(1:4, ~randn(2,2)))
  testthat::expect_s4_class(a, "matrix_list")
  testthat::expect_equal(class(element_of(a)), "list")
  testthat::expect_true(is_matrix(element_of(a)[[1]]))
  testthat::expect_error(new("matrix_list", matrices = 1))
})

testthat::test_that("Test Arithmetic", {
  set.seed(123)
  a <- new("matrix_list", matrices = purrr::map(1:4, ~randn(2,2)))
  testthat::expect_equal(a + 0, a)
  testthat::expect_equal(0 + a, a)
  testthat::expect_equal(a + a, 2 * a)
  testthat::expect_equal(a * 0, 0 * a)
  testthat::expect_equal(a - 0, a)
  testthat::expect_equal(0 - a, -a)
  testthat::expect_equal(a / 1, a)
  b <- randn(2,2)
  testthat::expect_silent(a %*% b)
  b2 <- randn(3,2)
  testthat::expect_error(a %*% b2)
})
