// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lcircledast
arma::mat lcircledast(arma::mat x, arma::mat y);
RcppExport SEXP _ADtools_lcircledast(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lcircledast(x, y));
    return rcpp_result_gen;
END_RCPP
}
// lboxdot
arma::mat lboxdot(arma::mat x, arma::mat y);
RcppExport SEXP _ADtools_lboxdot(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lboxdot(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcircledast
arma::mat rcircledast(arma::mat x, arma::mat y);
RcppExport SEXP _ADtools_rcircledast(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcircledast(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rboxdot
arma::mat rboxdot(arma::mat x, arma::mat y);
RcppExport SEXP _ADtools_rboxdot(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rboxdot(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ADtools_lcircledast", (DL_FUNC) &_ADtools_lcircledast, 2},
    {"_ADtools_lboxdot", (DL_FUNC) &_ADtools_lboxdot, 2},
    {"_ADtools_rcircledast", (DL_FUNC) &_ADtools_rcircledast, 2},
    {"_ADtools_rboxdot", (DL_FUNC) &_ADtools_rboxdot, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ADtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
