# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lcircledast <- function(x, y) {
    .Call('_ADtools_lcircledast', PACKAGE = 'ADtools', x, y)
}

lboxdot <- function(x, y) {
    .Call('_ADtools_lboxdot', PACKAGE = 'ADtools', x, y)
}

rcircledast <- function(x, y) {
    .Call('_ADtools_rcircledast', PACKAGE = 'ADtools', x, y)
}

rboxdot <- function(x, y) {
    .Call('_ADtools_rboxdot', PACKAGE = 'ADtools', x, y)
}

