# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcircledast <- function(x, y) {
    .Call(`_ADtools_rcircledast`, x, y)
}

rboxdot <- function(x, y) {
    .Call(`_ADtools_rboxdot`, x, y)
}

lboxdot <- function(x, y) {
    .Call(`_ADtools_lboxdot`, x, y)
}

lcircledast <- function(x, y) {
    .Call(`_ADtools_lcircledast`, x, y)
}

